version: "3.8"

services:
  # api service
  api:
    container_name: flask_api
    build:
      context: ./backend
      dockerfile: flask.Dockerfile
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=<connection string>
    depends_on:
      - db
    volumes:
      - ./backend:/app

  # db service
  db:
    container_name: oracle_db
    image: oracle/database:19.3.0-se2
    ports:
      - 1521:1521
    volumes:
      - oracle_data:/opt/oracle/oradata
    environment:
      - ORACLE_SID=<sid>
      - ORACLE_PWD=<password>

volumes:
  oracle_data:
