-- Drop tables
DROP TABLE QUIZZ_MEDIA;
DROP TABLE QUIZZ_APPLICATION;
DROP TABLE QUIZZ;
DROP TABLE GROUP_STUDENT;
DROP TABLE QWIKZGROUP;
DROP TABLE TEACHER;
DROP TABLE STUDENT; 
DROP TABLE INSTITUTION;

-- Drop sequences
DROP SEQUENCE STUDENT_SEQ;
DROP SEQUENCE INSTITUTION_SEQ;
DROP SEQUENCE TEACHER_SEQ;
DROP SEQUENCE QWIKZGROUP_SEQ;
DROP SEQUENCE GROUP_STUDENT_SEQ;
DROP SEQUENCE QUIZZ_SEQ;
DROP SEQUENCE QUIZZ_APPLICATION_SEQ;
DROP SEQUENCE QUIZZ_MEDIA_SEQ;

-- Drop tablespaces  
DROP TABLESPACE Applications
    INCLUDING CONTENTS AND DATAFILES
    CASCADE CONSTRAINTS;

DROP TABLESPACE Quizz
    INCLUDING CONTENTS AND DATAFILES
    CASCADE CONSTRAINTS;

DROP TABLESPACE Students  
    INCLUDING CONTENTS AND DATAFILES
    CASCADE CONSTRAINTS;

DROP TABLESPACE Teachers
    INCLUDING CONTENTS AND DATAFILES
    CASCADE CONSTRAINTS;