-- Eliminar el índice de clúster
DROP INDEX idx_quizz_cluster;

-- Eliminar el clúster (si hay tablas en el clúster, se eliminan también)
DROP CLUSTER quizz_cluster INCLUDING TABLES CASCADE CONSTRAINTS;
-- Deshabilitar las restricciones de claves foráneas
ALTER TABLE QUIZZ_QUESTIONS DROP CONSTRAINT FK_QUIZZ_QUESTIONS;
ALTER TABLE QUIZZ_APPLICATION DROP CONSTRAINT FK_QUIZZ_APP_QUIZZ;
ALTER TABLE QUIZZ_APPLICATION DROP CONSTRAINT FK_QUIZZ_APP_GROUP_STUDENT;
ALTER TABLE QUIZZ_MEDIA DROP CONSTRAINT FK_QUIZZ_MEDIA_QUIZZ;
ALTER TABLE GROUP_STUDENT DROP CONSTRAINT FK_GROUP_STUDENT_QWIKZGROUP;
ALTER TABLE GROUP_STUDENT DROP CONSTRAINT FK_GROUP_STUDENT_STUDENT;
ALTER TABLE QUIZZ DROP CONSTRAINT FK_QUIZZ_QWIKZGROUP;
ALTER TABLE QWIKZGROUP DROP CONSTRAINT FK_QWIKZGROUP_TEACHER;
ALTER TABLE TEACHER DROP CONSTRAINT FK_TEACHER_INSTITUTION;
ALTER TABLE STUDENT DROP CONSTRAINT FK_STUDENT_INSTITUTION;

-- Eliminar las tablas
DROP TABLE QUIZZ_QUESTIONS;
DROP TABLE QUIZZ_APPLICATION;
DROP TABLE QUIZZ_MEDIA;
DROP TABLE QUIZZ;
DROP TABLE GROUP_STUDENT;
DROP TABLE QWIKZGROUP;
DROP TABLE TEACHER;
DROP TABLE STUDENT;
DROP TABLE INSTITUTION;

-- Eliminar las secuencias
DROP SEQUENCE STUDENT_SEQ;
DROP SEQUENCE TEACHER_SEQ;
DROP SEQUENCE QWIKZGROUP_SEQ;
DROP SEQUENCE QUIZZ_SEQ;
DROP SEQUENCE QUIZZ_APPLICATION_SEQ;
DROP SEQUENCE QUIZZ_MEDIA_SEQ;
DROP SEQUENCE INSTITUTION_SEQ;
DROP SEQUENCE GROUP_STUDENT_SEQ;

-- Eliminar los tablespaces
DROP TABLESPACE IndexData INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE Quizz INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE Teachers INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE Students INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE Applications INCLUDING CONTENTS AND DATAFILES;
