DECLARE
  l_blob1 BLOB;
  l_blob2 BLOB;
  l_blob3 BLOB;
  l_bfile1 BFILE := BFILENAME('GIFS_DIR', 'mad.gif');
  l_bfile2 BFILE := BFILENAME('GIFS_DIR', 'easy.gif');
  l_bfile3 BFILE := BFILENAME('GIFS_DIR', 'pedro.gif');
BEGIN
  -- Insertar el primer GIF
  INSERT INTO QUIZZ_GIF (MIN_SCORE, MAX_SCORE, GIF_BLOB)
  VALUES (0, 4, EMPTY_BLOB())
  RETURNING GIF_BLOB INTO l_blob1;

  DBMS_LOB.FILEOPEN(l_bfile1, DBMS_LOB.FILE_READONLY);
  DBMS_LOB.LOADFROMFILE(l_blob1, l_bfile1, DBMS_LOB.GETLENGTH(l_bfile1));
  DBMS_LOB.FILECLOSE(l_bfile1);

  -- Insertar el segundo GIF
  INSERT INTO QUIZZ_GIF (MIN_SCORE, MAX_SCORE, GIF_BLOB)
  VALUES (5, 7, EMPTY_BLOB())
  RETURNING GIF_BLOB INTO l_blob2;

  DBMS_LOB.FILEOPEN(l_bfile2, DBMS_LOB.FILE_READONLY);
  DBMS_LOB.LOADFROMFILE(l_blob2, l_bfile2, DBMS_LOB.GETLENGTH(l_bfile2));
  DBMS_LOB.FILECLOSE(l_bfile2);

  -- Insertar el tercer GIF
  INSERT INTO QUIZZ_GIF (MIN_SCORE, MAX_SCORE, GIF_BLOB)
  VALUES (8, 10, EMPTY_BLOB())
  RETURNING GIF_BLOB INTO l_blob3;

  DBMS_LOB.FILEOPEN(l_bfile3, DBMS_LOB.FILE_READONLY);
  DBMS_LOB.LOADFROMFILE(l_blob3, l_bfile3, DBMS_LOB.GETLENGTH(l_bfile3));
  DBMS_LOB.FILECLOSE(l_bfile3);
END;
/
